apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: edassist-mightymaharaja-tk-tls
spec:
  secretName: edassist-mightymaharaja-tk #secret used to store the tls certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: edassist.mightymaharaja.tk
  dnsNames: #these domain names will be on the certificate
    - edassist.mightymaharaja.tk
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains: # the http challenge will be for the following domains
          - edassist.mightymaharaja.tk