# Generated by Django 3.0.4 on 2020-03-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('course_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.CharField(max_length=400)),
                ('level', models.CharField(max_length=25)),
                ('features', models.CharField(blank=True, max_length=300, null=True)),
                ('complete_video', models.BooleanField(blank=True, null=True)),
                ('complete_audio', models.BooleanField(blank=True, null=True)),
                ('other_video', models.BooleanField(blank=True, null=True)),
                ('other_audio', models.BooleanField(blank=True, null=True)),
                ('online_textbooks', models.BooleanField(blank=True, null=True)),
                ('complete_lectures', models.BooleanField(blank=True, null=True)),
                ('assesments_with_solution', models.BooleanField(blank=True, null=True)),
                ('student_projects', models.BooleanField(blank=True, null=True)),
                ('instructor_insights', models.BooleanField(blank=True, null=True)),
                ('instructors', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'courses',
                'managed': False,
            },
        ),
    ]
