# Generated by Django 3.0.4 on 2020-03-18 15:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('disciplinename', models.CharField(max_length=50)),
                ('subjectid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('subjectname', models.CharField(max_length=200)),
                ('institute', models.CharField(max_length=100)),
                ('medium', models.CharField(max_length=20)),
                ('state', models.BooleanField(blank=True, null=True)),
                ('extra_downloads', models.BooleanField(blank=True, null=True)),
                ('coordinators', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtraDownloads',
            fields=[
                ('download_link', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('module_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'extra_downloads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('subjectid', models.ForeignKey(db_column='subjectid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='nptel.Courses')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('youtube_id', models.CharField(blank=True, max_length=20, null=True)),
                ('lecture_number', models.SmallIntegerField()),
                ('video_download', models.CharField(blank=True, max_length=400, null=True)),
                ('pdf_download', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'lectures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YoutubeStuff',
            fields=[
                ('youtube_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('caption_name', models.CharField(max_length=100)),
                ('captions', models.TextField()),
                ('important_words', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'youtube_stuff',
                'unique_together': {('youtube_id', 'caption_name')},
            },
        ),
    ]
